In [1]:
# 1) Convert the below list into numpy array then display array

import numpy as np

my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [2]:
# 2) Convert the below list into a numpy array then display the array then display the first and last
# index and then multiply each elemnt by 2 and display the result

my_list=[1,2,3,4,5]
arr=np.array(my_list)
print("Array:",arr)
print("First  element:",arr[0])
print("Last  element:",arr[-1])
print("Array after doubling each element")
print(arr*2)

Array: [1 2 3 4 5]
First  element: 1
Last  element: 5
Array after doubling each element
[ 2  4  6  8 10]


In [3]:
# 3) Write a Numpy program to create an array of 10 zeros,10 ones and 10 fives
zero_arr=np.zeros(10)
print("An array of 10 zeros")
print(zero_arr)

one_arr=np.ones(10)
print("An array of 10 ones")
print(one_arr)

five_arr=np.ones(10)*5
print("An array of 10 fives")
print(five_arr)

An array of 10 zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [4]:
# 4) Write a numpy program to create a 3*3 matrix with values 2 to 10
import numpy as n
mat=np.array([2,3,4,5,6,7,8,9,10]).reshape(3,3)
print("Matrix(3*3):")
print(mat)


Matrix(3*3):
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
