In [1]:
# 1. Suppose you have a dataset containing daily temperature readings for a city, and you
# want to identify days with extreme temperature conditions. Find days where the
# temperature either exceeded 35 degrees Celsius (hot day) or dropped below 5 degrees
# Celsius (cold day).

import numpy as np
temperatures = np.array([32.5, 34.2, 36.8, 29.3, 31.0, 38.7, 23.1, 18.5, 22.8, 37.2,4.0,-4.0,-12.0])
hot_days=np.where(temperatures>35)
cold_days=np.where(temperatures<5)

print("Hot Days:")
print("Day", "Temperature(C)")
for day in hot_days[0]:
    print(day+1, temperatures[day], sep='\t')

print()
print("Cold Days:")
print("Day", "Temperature(C)")
for day in cold_days[0]:
    print(day+1, temperatures[day],sep='\t')

Hot Days:
Day Temperature(C)
3	36.8
6	38.7
10	37.2

Cold Days:
Day Temperature(C)
11	4.0
12	-4.0
13	-12.0


In [2]:
# 2. Suppose you have a dataset containing monthly sales data for a company, and you
# want to split this data into quarterly reports for analysis and reporting purposes.

monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

quarterly_sales = np.split(monthly_sales, 4)
n=len(quarterly_sales)
for i in range(0,n-1,1):
    print("Quater ",i ,"Sales(in thousand Dollars):")
    print(quarterly_sales[i])

Quater  0 Sales(in thousand Dollars):
[120 135 148]
Quater  1 Sales(in thousand Dollars):
[165 180 155]
Quater  2 Sales(in thousand Dollars):
[168 190 205]


In [3]:
# 3. Suppose you have a dataset containing customer data, and you want to split this data
# into two groups: one group for customers who made a purchase in the last 30 days and
# another group for customers who haven't made a purchase in the last 30 days.

customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])

recent_customers = customer_ids[last_purchase_days_ago <= 30]
old_customers = customer_ids[last_purchase_days_ago > 30]

print("Active Customers (Last Purchase<=30 days)")
print(recent_customers)
print()
print("Inactive Customers (Last Purchase>30 days)")
print(old_customers)

Active Customers (Last Purchase<=30 days)
[101 102 103 104 105]

Inactive Customers (Last Purchase>30 days)
[106 107 108 109 110]


In [5]:
# 4.Suppose you have two sets of employee data—one containing information about
# full-time employees and another containing information about part-time employees. You
# want to combine this data to create a comprehensive employee dataset for HR analysis.

# Employee data for full-time employees
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])

# Employee data for part-time employees
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])

combined_employees = np.vstack((full_time_employees, part_time_employees))
n=len(combined_employees)

print("Combined Employee data")
for i in range(0,n,1):
    print("Employee id",combined_employees[i][0],"Name:",combined_employees[i][1],"Type",combined_employees[i][2],"Salary",combined_employees[i][3])

Combined Employee data
Employee id 101 Name: John Doe Type Full-Time Salary 55000
Employee id 102 Name: Jane Smith Type Full-Time Salary 60000
Employee id 103 Name: Mike Johnson Type Full-Time Salary 52000
Employee id 201 Name: Alice Brown Type Part-Time Salary 25000
Employee id 202 Name: Bob Wilson Type Part-Time Salary 28000
Employee id 203 Name: Emily Davis Type Part-Time Salary 22000
