In [3]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

sub_arrays=np.split(arr,3)

for sub in sub_arrays:
    print(sub)



[1 2]
[3 4]
[5 6]


In [2]:
import numpy as np
arr=np.array([3,1,2,4,5])

sorted_arr=np.sort(arr)
print("Ascending",sorted)

sorted_arr1=np.sort(arr)[::-1]
print("Descending",sorted_arr1)

Ascending <built-in function sorted>
Descending [5 4 3 2 1]


In [4]:
import numpy as np

matrix=np.array([[3,1,2],[6,5,4]])
sorted_matrix=np.sort(matrix,axis=1)
print("Sorted Matrix",sorted_matrix)

Sorted Matrix [[1 2 3]
 [4 5 6]]


In [8]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.concatenate((arr1,arr2),axis=1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
rr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6]])
result=np.concatenate((arr1,arr2),axis=0)
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [12]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [13]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=np.hstack((arr1,arr2))
print(result)

[1 2 3 4 5 6]


In [15]:
import numpy as np
# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])
# Create a boolean mask based on a condition (e.g., values greater than 3)
mask = (arr > 3)
# Use the mask to filter elements in the array
filtered_array = arr[mask]
# Print the filtered array
print("Filtered Array:", filtered_array)

Filtered Array: [4 5 6]


In [18]:
prd_b=np.array([2,8])
prdB_var=np.var(prd_b)
print("Varianc:",prdB_var)
print("SD",np.std(prd_b))

Varianc: 9.0
SD 3.0


In [24]:
classA= np.array([85, 88, 90, 92, 95])
classB= np.array([70, 80, 85, 95, 100])
print("Mean of A",np.mean(classA))
print("Mean of B",np.mean(classB))
print("Var A",np.var(classA))
print("Var B",np.var(classB))
classA_std=np.std(classA)
classB_std=np.std(classB)
print('Class A Standard Deviation',classA_std )
print('Class B Standard Deviation',classB_std )

Mean of A 90.0
Mean of B 86.0
Var A 11.6
Var B 114.0
Class A Standard Deviation 3.40587727318528
Class B Standard Deviation 10.677078252031311


In [25]:
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136])
median = np.percentile(test_scores, 50)
print("Median (50th Percentile):", median)

Median (50th Percentile): 108.0


In [26]:
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108,
110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136])
q1 = np.percentile(test_scores, 25)
print("Lower Quartile (25th Percentile):", q1)

Lower Quartile (25th Percentile): 95.0


In [27]:
import numpy as np
# Sample student scores
scores = np.array([85, 92, 78, 88, 95, 72, 89])

# Save the scores to a file
np.save('student_scores.npy', scores)

# Load the scores from the file
loaded_scores = np.load('student_scores.npy')

print("Original Scores:", scores)
print("Loaded Scores:", loaded_scores)


Original Scores: [85 92 78 88 95 72 89]
Loaded Scores: [85 92 78 88 95 72 89]
