In [2]:
import numpy as np

arr=np.array([10,20,330,25,6,2])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sin(arr))
print(np.cos(arr))

2
330
5
2
[-0.54402111  0.91294525 -0.13238163 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206 -0.99119882  0.99120281  0.96017029 -0.41614684]


In [15]:
np.random.seed(122)
mat=np.random.randint(1,21,9).reshape(3,3)
print(mat)
print("Sum of Matrix:",np.sum(mat))
print("Cumsum of matrix",np.cumsum(mat))
print("Minnimum element:",np.min(mat))
print("Maximum element ",np.max(mat))

[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
Sum of Matrix: 116
Cumsum of matrix [ 16  27  40  57  70  86  89 105 116]
Minnimum element: 3
Maximum element  17


In [17]:
# axis=1 for row and 0 is for column
#for row
print("Sum of Matrix:",np.sum(mat,axis=1))
print("Cumsum of matrix",np.cumsum(mat,axis=1))
print("Minnimum element:",np.min(mat,axis=1))
print("Maximum element ",np.max(mat,axis=1))

Sum of Matrix: [40 46 30]
Cumsum of matrix [[16 27 40]
 [17 30 46]
 [ 3 19 30]]
Minnimum element: [11 13  3]
Maximum element  [16 17 16]


In [18]:
# axis=0 for column
# for column
print(np.sum(mat,axis=0))
print(np.cumsum(mat,axis=0))
print(np.min(mat,axis=0))
print(np.max(mat,axis=0))

[36 40 40]
[[16 11 13]
 [33 24 29]
 [36 40 40]]
[ 3 11 11]
[17 16 16]


In [14]:
print(np.sum(mat,axis=-1))
print(np.cumsum(mat,axis=-1))
print(np.min(mat,axis=-1))
print(np.max(mat,axis=-1))

[40 46 30]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]
[11 13  3]
[16 17 16]
