In [1]:
import numpy as np

a = np.array(40)
b = np.array([1,2,3,4,5])
c = np.array([[12,22,13,23],[33,21,11,22]])
d = np.array([[[16,55,23,43],[56,66,33,90],[76,4,33,15]]])

print("Array A\n",a)
print("--------------------------")
print("Array B\n",b)
print("--------------------------")
print("Array C\n",c)
print("--------------------------")
print("Array D\n",d)
print("--------------------------")
print("A array dimension",a.ndim)
print("B array dimension",b.ndim)
print("C array dimension",c.ndim)
print("D array dimension",d.ndim)

Array A
 40
--------------------------
Array B
 [1 2 3 4 5]
--------------------------
Array C
 [[12 22 13 23]
 [33 21 11 22]]
--------------------------
Array D
 [[[16 55 23 43]
  [56 66 33 90]
  [76  4 33 15]]]
--------------------------
A array dimension 0
B array dimension 1
C array dimension 2
D array dimension 3


In [2]:
b = np.array([1,2,3,4,5])
b1 = b[1:5]
b1[2]=200
print(b1)
print(b)

[  2   3 200   5]
[  1   2   3 200   5]


In [3]:
arr = np.array([1,2,3,4,5])
arr2 = arr.copy()
print("original array without change",arr)
arr[0] = 42
print("original array with change",arr)
print("Copy of Original Array",arr2)

original array without change [1 2 3 4 5]
original array with change [42  2  3  4  5]
Copy of Original Array [1 2 3 4 5]


In [8]:
arr = np.array([1,2,3,4,5])
x = arr.view() # replica create
arr[0]=43
print(arr)
print(x)

[43  2  3  4  5]
[43  2  3  4  5]


In [5]:
arr = np.ones([3,4])
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
arr = np.eye(4)
print(arr)  #print the elements Diagonally

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
arr = np.diag([3,4,1,2]) # print different elements diagonally
print(arr)

[[3 0 0 0]
 [0 4 0 0]
 [0 0 1 0]
 [0 0 0 2]]


In [11]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.diag(arr))

[1 5 9]


In [12]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [14]:
rand=np.random.randint(0,10,3)
print(rand)

[5 9 2]


In [17]:
rand=np.random.randint(2,3)
print(rand)

2


In [21]:
arr=np.random.randint(0,100,12)
print(arr)
arr=arr.reshape(4,3)
print(arr)
print("Array Values is ",arr[0][1])
print("Array Values is ",arr[1][0])
print(arr.shape)
arr=arr.reshape(-1,4)
print(arr,arr.shape)
arr.reshape(2,-1)
print(arr,arr.shape)

[18 31 70 53 70 87 21 20 92 47 87 24]
[[18 31 70]
 [53 70 87]
 [21 20 92]
 [47 87 24]]
Array Values is  31
Array Values is  53
(4, 3)
[[18 31 70 53]
 [70 87 21 20]
 [92 47 87 24]] (3, 4)
[[18 31 70 53]
 [70 87 21 20]
 [92 47 87 24]] (3, 4)


In [24]:
np.random.seed(145)
arr=np.random.randint(0,100,12)
print(arr)

[37 86 87 18 90 69  8 53 33 32 40 26]


In [27]:
np.random.seed(111)
arr=np.random.randint(1,500,30).reshape(6,5)
print(arr)
print(arr[2:,2:])
print(arr[3:5,2:4])

[[341 365 469 213  87]
 [276 170 323 119 467]
 [297 456 442   8 269]
 [267 450 369 217 285]
 [271 419  22  55 201]
 [ 38 461 231 187 269]]
[[442   8 269]
 [369 217 285]
 [ 22  55 201]
 [231 187 269]]
[[369 217]
 [ 22  55]]


In [30]:
arr=np.array([1,20,5,9,3,4,8,5,6,2,25,2,2265,3])
slicing=arr[4:9]
print("old slicing",slicing)
print("old array",arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print("new slicing",slicing)
print("new array",arr)

old slicing [3 4 8 5 6]
old array [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
new slicing [0 0 0 0 0]
new array [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3]


In [38]:
arr=np.arange(1,15)
print(arr)
print(arr[arr%2==0])
print(arr[arr%2!=0])
print(arr[arr>8])
arr[arr%2==0]=0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]
[ 1  3  5  7  9 11 13]
[ 9 10 11 12 13 14]
[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0]


In [44]:
arr=np.arange(1,8)
print(arr)
print(arr+2)
print(arr*2)
print(arr**2)

[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]
