In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
indices=np.where(arr>3)
print(indices)

(array([3, 4, 5, 6, 7]),)


In [4]:
arr=np.array([[1,2,3],[4,5,6]])

# Transpose the array using rows and column
transpose_arr=np.transpose(arr)
print(transpose_arr)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
arr=np.array([1,2,3,4,6,7,8])
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))

Mean: 4.428571428571429
Median: 4.0


In [15]:
sorted_array=np.array([1,4,7,9])
index=np.searchsorted(sorted_array,5)
print("New element inserted at index:",index)

New element inserted at index: 2


In [19]:
arr=np.array([1,2,3,5,4,8,9])
new_arr=np.extract(arr>3,arr)
print("Elements greater than 3:")
print(new_arr)

Elements greater than 3:
[5 4 8 9]
